# Generated by Django 4.2.6 on 2023-11-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_alter_highest_score_alter_snippet_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='answer',
            field=models.CharField(choices=[('choice1', 1), ('choice2', 2), ('choice3', 3), ('choice4', 4)], default='1', max_length=500),
        ),
    ]
