# Generated by Django 4.2.6 on 2023-11-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_alter_snippet_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='answer',
            field=models.IntegerField(default=1),
        ),
    ]
