# Generated by Django 4.2.6 on 2023-11-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_alter_snippet_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='answer',
            field=models.CharField(choices=[(0, 1), (1, 2), (2, 3), (3, 4)], default='1', max_length=500),
        ),
    ]
