# Generated by Django 3.2.22 on 2023-11-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_alter_snippet_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='answer',
            field=models.CharField(choices=[('1', 'Choice 1'), ('2', 'Choice 2'), ('3', 'Choice 3'), ('4', 'Choice 4')], default='1', max_length=1),
        ),
    ]
