# Generated by Django 4.2.6 on 2023-11-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_highest_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highest',
            name='input',
        ),
        migrations.RemoveField(
            model_name='highest',
            name='name',
        ),
        migrations.AlterField(
            model_name='highest',
            name='score',
            field=models.JSONField(),
        ),
    ]
